NAME = guitest
#SRCS = imgui_impl_sdl.cpp main.cpp
SRCS = guitest-am.cpp
INC_DIR += $(AM_HOME)/libs/imgui/include
LINK_FILES += $(AM_HOME)/libs/imgui/build/imgui-$(ARCH).a

include $(AM_HOME)/Makefile.app
