#!/bin/bash
make || exit

rm -f trace.log
qemu-system-i386 \
  -smp 6 \
  -chardev stdio,mux=on,id=char0 \
  -chardev file,path=trace.log,id=char1 \
  -serial chardev:char0 \
  -serial chardev:char1 \
  build/mptest-x86-qemu; hd trace.log
