ifneq ($(MAKECMDGOALS),clean) # ignore check for make clean

ifeq ($(AM_HOME),) # AM_HOME must exist
$(error Environment variable AM_HOME must be defined.)
endif

ARCH  ?= native
ARCHS := $(basename $(notdir $(shell ls $(AM_HOME)/am/arch/*.mk)))

ifeq ($(filter $(ARCHS), $(ARCH)), ) # ARCH must be valid
$(error Invalid ARCH. Supported: $(ARCHS))
endif

ARCH_SPLIT  = $(subst -, ,$(ARCH))
ISA        ?= $(word 1,$(ARCH_SPLIT))
PLATFORM   ?= $(word 2,$(ARCH_SPLIT))

endif
