#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/cmovcc.h"
#include "data-mov/xchg.h"
#include "data-mov/push.h"
#include "data-mov/pop.h"
#include "data-mov/movzx.h"
#include "data-mov/leave.h"
#include "data-mov/movsx.h"
#include "data-mov/cvw.h"
#include "data-mov/in.h"
#include "data-mov/out.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"
#include "arith/cmp.h"
#include "arith/sub.h"
#include "arith/add.h"
#include "arith/adc.h"
#include "arith/sbb.h"
#include "arith/neg.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"
#include "logic/test.h"
#include "logic/setcc.h"
#include "logic/bt.h"

#include "string/rep.h"
#include "string/movs.h"
#include "string/stos.h"
#include "string/cmps.h"

#include "misc/misc.h"
#include "misc/lgdt.h"
#include "misc/lidt.h"
#include "misc/int.h"

#include "ctrl-tran/call.h"
#include "ctrl-tran/ret.h"
#include "ctrl-tran/jcc.h"
#include "ctrl-tran/jmp.h"


#include "special/special.h"
