lib-$(CONFIG_RV_IOMMU_REF_C_MODEL) += build_ddt.o
lib-$(CONFIG_RV_IOMMU_REF_C_MODEL) += build_g_stage_pt.o
lib-$(CONFIG_RV_IOMMU_REF_C_MODEL) += build_pdt.o
lib-$(CONFIG_RV_IOMMU_REF_C_MODEL) += build_s_stage_pt.o
lib-$(CONFIG_RV_IOMMU_REF_C_MODEL) += build_vs_stage_pt.o
lib-$(CONFIG_RV_IOMMU_REF_C_MODEL) += translate_gpa.o
