NAME = iommu-st-new-openxiangshan

SRCS = main.c iommu_sys.c openxiangshan_dmac.c iommu_cache.S
LIBS += librv-iommu-reference-c_model
INC_DIR += $(AM_HOME)/libs/librv-iommu-reference-c_model

include $(AM_HOME)/Makefile.app
