#!/bin/bash

DIR=${AM_HOME}/am/arch/mips32-npc/img
DEST=$1
shift

bash -c "cd $DIR/boot && make"

mips-linux-gnu-ld --gc-sections -EL -T $DIR/loader.ld -e _start -o ${DEST} $DIR/boot/start.o --start-group $@ --end-group &&  \
python $DIR/instr_check.py ${DEST}
