NAME = bf16fast
SRCS = ../bf16/bf16.c ../bf16/test_scalar.c ../bf16/test_vec.c main.c
INC_DIR += $(APP_DIR)/../bf16/
MARCH ?= rv64gc_zba_zbb_zbc_zbs_zbkb_zbkc_zbkx_zknd_zkne_zknh_zkr_zksed_zksh_zkt_zfbfmin_zvfbfwma_zvfbfmin_zfhmin

include $(AM_HOME)/Makefile.app
